apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: {{ include "model-ops-model.fullname" . }}
spec:
  mounts:
    # 模型文件在，镜像中的存储位置
  - mountPoint: {{ .Values.modelMountPoint }}
    name: models-dir
---
apiVersion: data.fluid.io/v1alpha1
kind: ThinRuntime
metadata:
  name: {{ include "model-ops-model.fullname" . }}
spec:
  profileName: {{ include "model-ops-model.fullname" . }}
---
apiVersion: data.fluid.io/v1alpha1
kind: ThinRuntimeProfile
metadata:
  name: {{ include "model-ops-model.fullname" . }}
spec:
  {{- if .Values.imagePullSecrets.model }}
  imagePullSecrets:
  - name: {{ .Values.imagePullSecrets.model }}
  {{- end }}
  fileSystemType: thin
  fuse:
    image: {{ .Values.image.deploy.repository }}
    imageTag: {{ .Values.image.model.tag }}
    imagePullPolicy: {{ .Values.image.model.pullPolicy }}
    command:
    - bash
    - "/entrypoint.sh"
    # cleanPolicy: OnDemand
    volumeMounts:
    - name: model-image-entrypoint
      subPath: entrypoint.sh
      mountPath: /entrypoint.sh
    - name: model-image-fluid-config-init
      subPath: fluid_config_init.py
      mountPath: /fluid_config_init.py
  volumes:
  - name: model-image-fluid-config-init
    configMap:
      name: model-image-fluid-config-init
  - name: model-image-entrypoint
    configMap:
      name: model-image-entrypoint
